'use strict';

// Identify some global variables I might need

var productsArr = []
var imagesOnScreen = 3;
// Build a Constructor function


function ProductsImage(name, imgPath) {
  this.name = name;
  this.imgPath = imgPath;
  this.clickCount = 0;

  productsArr.push(this);
};



// build a function to push objects into the productsArr

// allProducts should take all values generated by the ProductsImage constructor and push them into the productsArr array

ProductsImage.prototype.render = function() {
  var target = document.getElementById('products');
  var newLi = document.createElement('li');

  var newP = document.createElement('p');
  newP.textContent = 'clicks: ' + this.clickCount;

  var newImg = document.createElement('img');
  newImg.src = this.imgPath;

  newLi.appendChild(newImg);
  newLi.appendChild(newP);

  target.appendChild(newLi);

}; 


new ProductsImage('bag', 'img/bag.jpg');
new ProductsImage('banana', 'img/banana.jpg');
new ProductsImage('bathroom', 'img/bathroom.jpg');
new ProductsImage('boots', 'img/boots.jpg');
// new ProductsImage('breakfast', 'img/breakfast.jpg');
// new ProductsImage('bubblegum', 'img/bubblegum.jpg');
// new ProductsImage('chair', 'img/chair.jpg');
// new ProductsImage('cthulhu', 'img/cthulhu.jpg');
// new ProductsImage('dog-duck', 'img/dog-duck.jpg');
// new ProductsImage('dragon', 'img/dragon.jpg');
// new ProductsImage('pen', 'img/pen.jpg');
// new ProductsImage('pet-sweep', 'img/pet-sweep.jpg');
// new ProductsImage('scissors', 'img/scissors.jpg');
// new ProductsImage('shark', 'img/shark.jpg');
// new ProductsImage('sweep', 'img/sweep.png');
// new ProductsImage('tauntaun', 'img/tauntaun.jpg');
// new ProductsImage('unicorn', 'img/unicorn.jpg');
// new ProductsImage('usb', 'img/usb.gif');
// new ProductsImage('water-can', 'img/water-can.jpg');
// new ProductsImage('wine-glass', 'img/wine-glass.jpg');

productsArr[0].render();
productsArr[1].render();
productsArr[2].render();
productsArr[3].render();