'use strict';

// Identify some global variables I might need

ProductsImage.productsArray = [];
// Build a Constructor function


function ProductsImage(name, imgPath) {
  this.name = name;
  this.imgPath = imgPath;
  this.clickCount = 0;
  this.views = 0;

  ProductsImage.productsArray.push(this);
  // console.log(ProductsImage.ProductsImage.productsArray);
};


var randomNumberArray = [];

function generateRandomNumber() {
  for (var i = 0; i < ProductsImage.productsArray.length; i++)
    var randomNumber = Math.floor(Math.random() * ProductsImage.productsArray.length);
  randomNumberArray.push(randomNumber);
};

generateRandomNumber();

// Now that I have generate a random number I can use it later to 



// build a function to push objects into the ProductsImage.ProductsImage.productsArray

// allProducts should take all values generated by the ProductsImage constructor and push them into the ProductsImage.ProductsImage.productsArray array

ProductsImage.prototype.render = function () {
  for (var i = 0; i < ProductsImage.productsArray.length; i++) {
    var target = document.getElementById('products');
    var newLi = document.createElement('li');

    var newP = document.createElement('p');
    newP.textContent = 'clicks: ' + this.clickCount;
    
    var newImg = document.createElement('img');
    newImg.src = this.imgPath;
    newImg.id = this.name;
    
    newLi.appendChild(newImg);
    newLi.appendChild(newP);
    target.appendChild(newLi);


  }
};

function putAllProductsOnPage() {
  console.log(ProductsImage.productsArray);
  // for (var i = 0; i < 2; i++) {
    ProductsImage.productsArray.render();
  // }
};


// render three images on page

// function putProductsOnPage() {
//   var target = document.getElementById('products');

//   target.innerHTML = 'Check out these products!'; // property on any tag, stands for all the inner html


//   for (var i = 0; i < ProductsImage.productsArray.length; i++) {
//     var randoIndex = Math.floor(Math.random() * randomNumberArray.length); // 0, 1, 2,3, 4
//     ProductsImage.productsArray[randoIndex].render();
//   }
// };


// ProductsImage.prototype.renderAllImages = function () {
//   for(var i = 0; i < ProductsImage.productsArray.length; i++){
//     ProductsImage.productsArray[i].render();
//   }
// };

// 

// ProductsImage.prototype.renderAllProductsToPage = function() {
//   for(var i = 0; i < this.ProductsImage.ProductsImage.productsArray.length; i++) {
//     var placeholder = ProductsImage.ProductsImage.productsArray.render();
//   }
// };

// var randomNumArray = [];


// function randomNum() {
//   // randomly pick first number
// var ulTarget = document.getElementById('products');
// ulTarget.innerHTML = '';
//   for (var i = 0; i < 3; i++) {
//     var randomNumber = Math.floor(Math.random() * this.ProductsImage.productsArray.length);
//     this.ProductsImage.productsArray[randomNumber].render();
//     this.ProductsImage.productsArray[randomNumber].views++

// };

// // compare second to first number and make they are different
// do {
//   var singleRandomNum = Math.floor(Math.random() * ProductsImage.ProductsImage.productsArray.length)
// } while (singleRandomNum === randomNumArray[0])
// randomNumArray.push(singleRandomNum);
// //compare third number to second and first and make sure they are not the same
// do {
//   var singleRandomNum = Math.floor(Math.random() * ProductsImage.ProductsImage.productsArray.length)
// } while (singleRandomNum === randomNumArray[0] || singleRandomNum === randomNumArray[1])
// randomNumArray.push(singleRandomNum);

// };

// create a click handler to log clicks by user

// function clickOnPicHandler () {

// // }
// var clicks = 0;

// function handleClickOnPic(eventPotato) { // there is almost always a paramater called event (injected by chrome) - scary javascript
//   if (clicks < 25) {
//     clicks++;
//     for (var i = 0; i < 3; i++) {
//       if (event.target.id === ProductsImage.productsArray[i].name) {
//         ProductsImage.productsArray[i].clickCount++;
//       }
//     }
//     randomNum();
//   }
//   if (clicks === 3) {
//     var ulTarget = document.getElementById('products');
//     ulTarget.innerHTML = '';
//     var target = document.getElementById('products');
//     var newP = document.createElement('p');
//     var newLi = document.createElement('li');
//     newP.textContent = ProductsImage.productsArray[0];
//     newLi.textContent = 'Total Views ' + ProductsImage.productsArray[0].views + ' Total Clicks ' + ProductsImage.productsArray[0].clickCount;
//     target.appendChild(newP);
//     target.appendChild(newLi);
//   }
// }



// function renderAllProductsToPage() {
//   var ulTarget = document.getElementById('products');
//   ulTarget.innerHTML = '';
//   for (var i = 0; i < 3; i++)
//     ProductsImage.ProductsImage.productsArray[i].render()
// };

// For every product in the array I want to display them randomly 3 at a time and perform this function 'x' amount of times as designated by lab.

// function renderThreeProductstoPage() {

// }


// (Math.floor(Math.random() * ProductsImage.ProductsImage.productsArray.length));

var bag = new ProductsImage('bag', 'img/bag.jpg');
var banana = new ProductsImage('banana', 'img/banana.jpg');
var bathroom = new ProductsImage('bathroom', 'img/bathroom.jpg');
var boots = new ProductsImage('boots', 'img/boots.jpg');
var breakfast = new ProductsImage('breakfast', 'img/breakfast.jpg');
var bubblegum = new ProductsImage('bubblegum', 'img/bubblegum.jpg');
var chair = new ProductsImage('chair', 'img/chair.jpg');
var cthulhu = new ProductsImage('cthulhu', 'img/cthulhu.jpg');
var dogduck = new ProductsImage('dog-duck', 'img/dog-duck.jpg');
var dragon = new ProductsImage('dragon', 'img/dragon.jpg');
var pen = new ProductsImage('pen', 'img/pen.jpg');
var petsweep = new ProductsImage('pet-sweep', 'img/pet-sweep.jpg');
var scissors = new ProductsImage('scissors', 'img/scissors.jpg');
var shark = new ProductsImage('shark', 'img/shark.jpg');
var sweep = new ProductsImage('sweep', 'img/sweep.png');
var tauntaun = new ProductsImage('tauntaun', 'img/tauntaun.jpg');
var unicorn = new ProductsImage('unicorn', 'img/unicorn.jpg');
var usb = new ProductsImage('usb', 'img/usb.gif');
var watercan = new ProductsImage('water-can', 'img/water-can.jpg');
var wineglass = new ProductsImage('wine-glass', 'img/wine-glass.jpg');

putAllProductsOnPage();

// renderAllImages();
// putProductsOnPage();
  // ProductsImage.ProductsImage.productsArray.render();
  // renderAllProductsToPage();
  // randomNum();
// }